cleandeps:
	rm -rf binutils* gcc* *.html
clonedeps:
	wget https://ftp.gnu.org/gnu/binutils/binutils-2.35.tar.gz
	wget https://ftp.gnu.org/gnu/gcc/gcc-9.3.0/gcc-9.3.0.tar.gz


check:
	# Check deps here https://wiki.osdev.org/GCC_Cross-Compiler
	# TODO: make this automatic